print("SYÖTÄ HENKILÖTIEDOT")
print("-------------------")
etunimet = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
puhelin = input("Anna puhelinnumero: ")
email = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
postinumero = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
vuosi = int(input("Anna syntymävuosi: "))
print("")
print("KIITOS!")
print("")
print("")
print("HENKILÖN TIEDOT")
print("---------------")
print("")
print("NIMI:")
print("\t" + sukunimi + ", " + etunimet)
print("PUH:")
print("  "+puhelin)
print("E-MAIL:")
print("  "+email)
print("OSOITE:")
print("  "+osoite)
print("  "+postinumero)
print("  "+kaupunki)
print("  "+maa)
print(f"Ikä: {2023-vuosi}")
