
print("SYÖTÄ HENKILÖTIEDOT")
print("-------------------")
etunimet = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
puhelin = input("Anna puhelinnumero: ")
email = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
postinumero = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
vuosi = int(input("Anna syntymävuosi: "))
print("")
print("KIITOS!")
print("")
print("")
print("HENKILÖN TIEDOT")
print("---------------")
print("")
print("NIMI:")
print("\t" + sukunimi + ", " + etunimet)
print("PUH:")
print("\t"+puhelin)
print("E-MAIL:")
print("\t"+email)
print("OSOITE:")
print("\t"+osoite)
print("\t"+postinumero)
print("\t"+kaupunki)
print("\t"+maa)
print(f"Ikä: {2023-vuosi}")
