print("*********************************")
print("*\t Valuuttamuunnin\t*")
print("*********************************")
dollari = float(input("Anna dollarin kurssi euroina: "))
euro = float(input("Anna rahan määrä euroina: "))
print(f"Rahan arvo dollareina: ", euro/dollari)
